// Generated by CoffeeScript 1.6.3
(function() {
  var BitterSet;

  module.exports = BitterSet = (function() {
    var ADDR_BITS, HAMMING_TABLE, WORD_BITS, bits, bstring, weight;

    WORD_BITS = 32;

    ADDR_BITS = 5;

    HAMMING_TABLE = [0, 1, 1, 2, 1, 2, 2, 3, 1, 2, 2, 3, 2, 3, 3, 4];

    weight = function(word) {
      return HAMMING_TABLE[(word >> 0x00) & 0xF] + HAMMING_TABLE[(word >> 0x04) & 0xF] + HAMMING_TABLE[(word >> 0x08) & 0xF] + HAMMING_TABLE[(word >> 0x0C) & 0xF] + HAMMING_TABLE[(word >> 0x10) & 0xF] + HAMMING_TABLE[(word >> 0x14) & 0xF] + HAMMING_TABLE[(word >> 0x18) & 0xF] + HAMMING_TABLE[(word >> 0x1C) & 0xF];
    };

    bits = function(word, offset) {
      var bit, _i, _ref, _results;
      if (offset == null) {
        offset = 0;
      }
      _results = [];
      for (bit = _i = 0, _ref = WORD_BITS - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; bit = 0 <= _ref ? ++_i : --_i) {
        if ((word & (1 << bit)) !== 0x0) {
          _results.push(bit + offset * WORD_BITS);
        }
      }
      return _results;
    };

    bstring = function(word) {
      return (word >>> 0).toString(2);
    };

    function BitterSet() {
      this.store = [];
    }

    BitterSet.prototype.get = function(bit) {
      return (this.store[bit >> ADDR_BITS] & (1 << bit)) !== 0x0;
    };

    BitterSet.prototype.set = function(bit) {
      this.store[bit >> ADDR_BITS] |= 1 << bit;
    };

    BitterSet.prototype.clear = function(bit) {
      if (bit != null) {
        this.store[bit >> ADDR_BITS] &= ~(1 << bit);
      } else {
        this.store = [];
      }
    };

    BitterSet.prototype.flip = function(bit) {
      this.store[bit >> ADDR_BITS] ^= 1 << bit;
    };

    BitterSet.prototype.next = function(value, from) {
      var length;
      length = this.length();
      while (from < length) {
        if (this.get(from) === value) {
          return from;
        }
        from += 1;
      }
      if (value === false) {
        return from;
      } else {
        return -1;
      }
    };

    BitterSet.prototype.previous = function(value, from) {
      while (!(from < 0)) {
        if (this.get(from) === value) {
          return from;
        }
        from -= 1;
      }
      return -1;
    };

    BitterSet.prototype.length = function() {
      var fill, tail;
      this.cull();
      if (this.store.length === 0) {
        return 0;
      }
      fill = WORD_BITS * (this.store.length - 1);
      tail = bstring(this.store[this.store.length - 1]).length;
      return fill + tail;
    };

    BitterSet.prototype.cardinality = function() {
      var reducer;
      reducer = function(sum, word) {
        return sum + weight(word);
      };
      return this.store.reduce(reducer, 0);
    };

    BitterSet.prototype.cull = function() {
      while (this.store.length > 0 && this.store[this.store.length - 1] === 0x0) {
        this.store.pop();
      }
    };

    BitterSet.prototype.or = function(set) {
      var i, _i, _ref;
      if (set === this) {
        return;
      }
      for (i = _i = 0, _ref = set.store.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        this.store[i] |= set.store[i];
      }
    };

    BitterSet.prototype.and = function(set) {
      var i, _i, _ref;
      if (set === this) {
        return;
      }
      for (i = _i = 0, _ref = this.store.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        this.store[i] &= set.store[i] || 0;
      }
      this.cull();
    };

    BitterSet.prototype.andnot = function(set) {
      var i, _i, _ref;
      if (set === this) {
        this.clear();
      } else {
        for (i = _i = 0, _ref = this.store.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          this.store[i] &= ~(set.store[i] || 0);
        }
        this.cull();
      }
    };

    BitterSet.prototype.xor = function(set) {
      var i, _i, _ref;
      if (set === this) {
        this.clear();
      } else {
        for (i = _i = 0, _ref = set.store.length; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          this.store[i] ^= set.store[i];
        }
        this.cull();
      }
    };

    BitterSet.prototype.toString = function() {
      var index, word;
      this.cull();
      return "\{" + ((function() {
        var _i, _len, _ref, _results;
        _ref = this.store;
        _results = [];
        for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
          word = _ref[index];
          _results.push(bits(word, index));
        }
        return _results;
      }).call(this)) + "\}";
    };

    BitterSet.prototype.toBinaryString = function() {
      var reducer;
      this.cull();
      reducer = function(string, word, index) {
        var fill;
        fill = index > 0 ? Array(WORD_BITS - string.length + 1).join('0') : '';
        return string + fill + bstring(word);
      };
      return this.store.reduce(reducer, '');
    };

    return BitterSet;

  })();

}).call(this);
